print('ini program saya')
print ('nama saya yilita')
print ('alamat saya koba')
print('hobi saya bermain bulu tangkis')
print('saya berasal dari kelas ilkom')
print('saya lahir di bangka tengah 25 oktober 2005')
